services:
  nginx:
    image: nginx:1.27-alpine
    platform: linux/amd64
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      api1:
        condition: service_started
      api2:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "20MB"

  api1:
    image: ghcr.io/israelaraujo70/rinha-2026:7a8adca
    platform: linux/amd64
    environment:
      API_ADDR: 0.0.0.0:8080
      INDEX_PATH: /index/data.bin
      IVF_NPROBE: "8"
      IVF_FULL_NPROBE: "64"
      KNN_TIMEOUT_US: "3000"
      RUST_LOG: warn
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "160MB"

  api2:
    image: ghcr.io/israelaraujo70/rinha-2026:7a8adca
    platform: linux/amd64
    environment:
      API_ADDR: 0.0.0.0:8080
      INDEX_PATH: /index/data.bin
      IVF_NPROBE: "8"
      IVF_FULL_NPROBE: "64"
      KNN_TIMEOUT_US: "3000"
      RUST_LOG: warn
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "160MB"
