services:
  haproxy:
    image: haproxy:3.3
    platform: linux/amd64
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - sockets:/sockets
    depends_on:
      api1:
        condition: service_started
      api2:
        condition: service_started
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "30MB"

  api1:
    image: rinha-2026:latest
    platform: linux/amd64
    build: .
    environment:
      SOCKET_PATH: /sockets/api1.sock
      INDEX_PATH: /index/data.bin
      IVF_NPROBE: "8"
      IVF_FULL_NPROBE: "24"
      KNN_TIMEOUT_US: "3000"
      RUST_LOG: warn
    volumes:
      - sockets:/sockets
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "160MB"

  api2:
    image: rinha-2026:latest
    platform: linux/amd64
    build: .
    environment:
      SOCKET_PATH: /sockets/api2.sock
      INDEX_PATH: /index/data.bin
      IVF_NPROBE: "8"
      IVF_FULL_NPROBE: "24"
      KNN_TIMEOUT_US: "3000"
      RUST_LOG: warn
    volumes:
      - sockets:/sockets
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "160MB"

volumes:
  sockets:
